### ISSUE TITLE
T is undefined in `cdf`

### ISSUE THREAD

**Issue by yurivish** [oschulz/EmpiricalDistributions.jl#8]
On this line: https://github.com/oschulz/EmpiricalDistributions.jl/blob/51f2a5303f2e3bb4b39177d29377083b8178b1d1/src/uv_binned_dist.jl#L94

I just found your package and was playing around, and tried to take the `cdf` of a `UvBinnedDist`.

It seems the type parameter was left off of the signature. Relatedly, the `where {T, N}` annotations on `mean`/`mode` etc. are not necessary, I think, since in those functions they aren't being referenced.

**Comment by oschulz** [comment]
Good catch, thanks @yurivish !

**Comment by oschulz** [comment]
New package version v0.3.0 getting registered right now. @yurivish , please do let me know if everything works for you - I made a lot of changes. I also added more tests, but there may still be new bugs.

**Comment by yurivish** [comment]
Thanks @oschulz! :)
